name: MagicArenas
version: ${project.version}
api-version: 1.13
authors: [NathanWolf, KmanCrazy]
main: com.elmakers.mine.bukkit.arenas.dueling.ArenasPlugin
depend: [Magic]
commands:
   arena:
     description: Admin commands for managing arenas
     usage: /arena [load, add, remove, describe, configure, start, stop, join, leave]
     permission: MagicArenas.commands.arena

permissions:
  MagicArenas.commands.arena:
    description: Player may use the base /arena command
    type: boolean
    default: op
  MagicArenas.commands.arena.load:
    description: Player may use the /arena load command
    type: boolean
    default: op
  MagicArenas.commands.arena.add:
    description: Player may use the /arena add command
    type: boolean
    default: op
  MagicArenas.commands.arena.remove:
    description: Player may use the /arena remove command
    type: boolean
    default: op
  MagicArenas.commands.arena.start:
    description: Player may use the /arena start command
    type: boolean
    default: op
  MagicArenas.commands.arena.stop:
    description: Player may use the /arena stop command
    type: boolean
    default: op
  MagicArenas.commands.arena.join:
    description: Player may use the /arena join command
    type: boolean
    default: op
  MagicArenas.commands.arena.leave:
    description: Player may use the /arena leave command
    type: boolean
    default: op
  MagicArenas.commands.arena.reset:
    description: Player may use the /arena reset command
    type: boolean
    default: op
  MagicArenas.commands.arena.join.other:
    description: Player may use the /arena join command on others
    type: boolean
    default: op
  MagicArenas.commands.arena.leave.other:
    description: Player may use the /arena leave command on others
    type: boolean
    default: op
  MagicArenas.signs.create:
    description: Player may create arena signs
    type: boolean
    default: op
  MagicArenas.signs.use:
    description: Player may use arena signs
    type: boolean
    default: true
